repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: .*devcontainer.json
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        language: python
  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args:
          - --disable=bad-continuation,duplicate-code,import-error
          - --ignore-patterns=test_
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --extend-ignore=E0401,E501
          - --max-line-length=90
          - --exclude=tests,test*.py
  - repo: local
    hooks:
      - id: check_reqs_all
        name: Check/Build requirements-all.txt
        entry: python -m tools.create_reqs_all
        pass_filenames: false
        language: python
        types: [python]
      - id: check_api_docs
        name: Check API docs for modules
        entry: python -m docs.generate_api_docs --source msticpy --api_path docs/source/api --temp docs/source/.api_tmp --ignore msticpy/sectools
        pass_filenames: false
        language: python
        types: [python]
