repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: .*devcontainer.json
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        language: python
  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        args:
          - --disable=bad-continuation,duplicate-code,import-error
          - --ignore-patterns=test_
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --extend-ignore=E0401,E501
          - --max-line-length=90
          - --exclude=tests,test*.py
  - repo: local
    hooks:
      - id: check_reqs_all
        name: Check/Build requirements-all.txt
        entry: python -m tools.create_reqs_all
        pass_filenames: false
        language: python
        types: [python]
      - id: check_data_queries
        name: Check docs for new queries
        entry: python -m docs.generate_query_docs
        files: msticpy/data/queries/*.yaml
        pass_filenames: false
        language: python
        types: [yaml]
      - id: check_api_docs
        name: Check API docs for modules
        entry: sphinx-apidoc
        args:
          - --o
          - docs/source/api
          - --force
          - --module-first
          - --separate
          - msticpy
          - msticpy/sectools
        pass_filenames: false
        language: python
        types: [python]
